spring.application.name=webapp
logging.level.com.openclassrooms.webapp=DEBUG
spring.output.ansi.enabled=always
spring.console.encoding=UTF-8
logging.level.org.springframework.boot.autoconfigure=ERROR
